# -*- coding: utf-8 -*-
"""IPAM-mosaicar_tiles_simples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qiO3N5RtaKOltLVBGBQnr1cGpltI3et
"""

# ⬇️ Instalar GDAL e tqdm (só precisa rodar uma vez no Colab)
!apt-get update -qq && apt-get install -y -qq gdal-bin python3-gdal
!pip install -q tqdm

# 📦 IMPORTAÇÕES
import os
import re
import shutil
import argparse
import subprocess
from glob import glob
from tqdm import tqdm

# 📂 Montar Drive
from google.colab import drive
drive.mount('/content/drive')

import os
import re
import shutil
import argparse
import subprocess
from glob import glob
from tqdm import tqdm
from osgeo import gdal # Importar a biblioteca GDAL Python

# Regex para detectar sufixo de timestamp "-1234567890-0987654321"
TIMESTAMP_RE = re.compile(r"\d{10}-\d{10}$")

def ensure_dir(path): os.makedirs(path, exist_ok=True)

def has_gdal():
    try:
        subprocess.run(["gdalbuildvrt","--version"],stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=True)
        subprocess.run(["gdal_translate","--version"],stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=True)
        return True
    except: return False

def list_tifs_recursive(input_dir):
    return [p for p in glob(os.path.join(input_dir,"**","*.tif"),recursive=True)]

def parse_datatype(path):
    """
    Extrai o prefixo do arquivo sem o sufixo de timestamp.
    Ex.: areaXYZ-1234567890-0987654321.tif -> areaXYZ
    """
    base = os.path.basename(path)
    name = os.path.splitext(base)[0]
    if TIMESTAMP_RE.search(name):
        clean = name[:-21]  # remove "-1234567890-0987654321"
    else:
        clean = name
    return clean

def plan_groups(files):
    """Agrupa arquivos pelo 'tipo' (prefixo)."""
    groups={}
    for f in files:
        dt=parse_datatype(f)
        groups.setdefault(dt,[]).append(f)
    return groups

def output_path_for_group(output_dir, dt):
    ensure_dir(output_dir)
    return os.path.join(output_dir,f"{dt}.tif")

def copy_single_file(src,dst_dir):
    ensure_dir(dst_dir)
    base=os.path.basename(src)
    dst=os.path.join(dst_dir,base)
    # Always remove existing file before copying to ensure a fresh copy
    if os.path.exists(dst):
        os.remove(dst)
        print(f"[INFO] Arquivo existente removido para cópia: {dst}")
    shutil.copy2(src,dst)
    return True,dst

def mosaic_files(inputs,output_file):
    # If output_file exists, remove it to ensure a fresh mosaic.
    if os.path.exists(output_file):
        os.remove(output_file)
        print(f"[INFO] Arquivo existente removido para mosaico: {output_file}")

    vrt=os.path.splitext(output_file)[0]+".vrt"
    try:
        # 1. Create VRT
        res=subprocess.run(["gdalbuildvrt",vrt]+inputs,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
        if res.returncode!=0: print("[ERRO] gdalbuildvrt:",res.stderr.strip()); return False

        # 2. Translate VRT to GeoTIFF
        res=subprocess.run(["gdal_translate","-of","GTiff",
                            "-co","TILED=YES","-co","COMPRESS=LZW","-co","PREDICTOR=2",
                            "-co","BIGTIFF=YES","-co","SPARSE_OK=TRUE",vrt,output_file],
                           stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True)
        if res.returncode!=0: print("[ERRO] gdal_translate:",res.stderr.strip()); return False

        # (Removed the explicit band description copying from VRT, we'll do it post-mosaicking)
        return True
    finally:
        # Ensure VRT is removed even if errors occur
        if os.path.exists(vrt): os.remove(vrt)

def set_band_descriptions(tif_path, descriptions):
    """
    Define as descrições das bandas em um arquivo GeoTIFF.
    """
    try:
        ds = gdal.Open(tif_path, gdal.GA_Update)
        if ds is None:
            print(f"[ERRO] Não foi possível abrir o arquivo TIFF para atualizar descrições de banda: {tif_path}")
            return False

        if ds.RasterCount != len(descriptions):
            print(f"[ALERTA] O número de bandas ({ds.RasterCount}) não corresponde ao número de descrições ({len(descriptions)}).")
            # Proceeding anyway, but this might indicate an issue.

        for i in range(ds.RasterCount):
            band = ds.GetRasterBand(i + 1)
            if i < len(descriptions):
                band.SetDescription(descriptions[i])
            else:
                print(f"[ALERTA] Sem descrição disponível para a banda {i+1}.")

        ds = None  # Fecha o dataset para salvar as alterações
        print(f"[INFO] Descrições de banda atualizadas para: {tif_path}")
        return True
    except Exception as e:
        print(f"[ERRO] Falha ao definir descrições de banda para {tif_path}: {e}")
        return False

def run(input_dir,output_dir,dry_run=False):
    if not os.path.isdir(input_dir): raise SystemExit(f"[ERRO] Pasta não existe: {input_dir}")
    ensure_dir(output_dir)

    # Temporary directory for intermediate processing on Colab's fast local disk
    TEMP_PROCESS_DIR = "/content/temp_mosaic_output"
    ensure_dir(TEMP_PROCESS_DIR)

    files=list_tifs_recursive(input_dir)
    print(f"[INFO] {len(files)} arquivos encontrados")
    groups=plan_groups(files)
    print(f"[INFO] {len(groups)} grupos identificados")

    needs_gdal=False; plan=[]
    for dt,flist in sorted(groups.items()):
        final_output_file = output_path_for_group(output_dir,dt)

        # Determine if we need to process this group:
        # We process if the main multi-band file does NOT exist in OUTPUT_DIR.
        # This simplifies planning. If the main file exists, we assume per-year files are also handled.
        if os.path.exists(final_output_file):
            plan.append((dt,len(flist),"PULAR (já existe no Drive)",final_output_file))
            continue

        temp_output_file = os.path.join(TEMP_PROCESS_DIR,f"{dt}.tif") # Use temp dir for operations
        if len(flist)==1: plan.append((dt,len(flist),"COPIAR",final_output_file))
        else: plan.append((dt,len(flist),"MOSAICAR",final_output_file)); needs_gdal=True

    print("\n[PLANO]:")
    for dt,n,act,out in plan: print(f" {dt} | {n} arquivos | {act} -> {out}")
    if dry_run: return

    if needs_gdal and not has_gdal(): raise SystemExit("[ERRO] GDAL não encontrado")

    print("\n[EXECUTANDO]...")
    for dt,flist in tqdm(sorted(groups.items())):
        final_output_file = output_path_for_group(output_dir,dt)

        # Re-check existence as a safety measure before processing
        if os.path.exists(final_output_file):
            print(f"[INFO] Pulando {final_output_file} (já existe no Drive).")
            continue

        temp_output_file = os.path.join(TEMP_PROCESS_DIR,f"{dt}.tif")

        # Get band descriptions from the first source file for this group
        band_descriptions_from_source = []
        try:
            src_ds = gdal.Open(flist[0], gdal.GA_ReadOnly)
            if src_ds:
                for i in range(src_ds.RasterCount):
                    band_descriptions_from_source.append(src_ds.GetRasterBand(i + 1).GetDescription())
                src_ds = None
        except Exception as e:
            print(f"[ALERTA] Não foi possível ler descrições de banda do arquivo fonte {flist[0]}: {e}")

        # Perform mosaicking/copying to temporary location on /content/
        if len(flist)==1:
            # For single files, copy directly to temp_output_file
            ok,final=copy_single_file(flist[0], TEMP_PROCESS_DIR)
            if ok: print(f"[CÓPIA TEMPORÁRIA] {temp_output_file}")
            else: print(f"[ERRO] Falha na cópia temporária de {flist[0]}"); continue
        else:
            # For multiple files, mosaic to temp_output_file
            if not mosaic_files(flist,temp_output_file):
                print(f"[ERRO] Falha no mosaico temporário para {temp_output_file}"); continue
            else:
                print(f"[MOSAICO TEMPORÁRIO] {temp_output_file}")

        # Apply band descriptions to the temporary file
        if band_descriptions_from_source:
            if not set_band_descriptions(temp_output_file, band_descriptions_from_source):
                print(f"[ALERTA] Falha ao atualizar descrições de banda para {temp_output_file}")

        # Move the final processed file from temp to final destination on Drive
        try:
            shutil.move(temp_output_file, final_output_file)
            print(f"[MOVENDO PARA DRIVE] {final_output_file}")
        except Exception as e:
            print(f"[ERRO] Falha ao mover {temp_output_file} para {final_output_file}: {e}")

    print("\n[FINALIZADO] Saídas em:",output_dir)

    # Clean up temporary directory
    if os.path.exists(TEMP_PROCESS_DIR):
        try:
            shutil.rmtree(TEMP_PROCESS_DIR)
            print(f"[LIMPEZA] Diretório temporário removido: {TEMP_PROCESS_DIR}")
        except Exception as e:
            print(f"[ALERTA] Falha ao remover diretório temporário {TEMP_PROCESS_DIR}: {e}")

# ▶️ Rodar mosaico com suas pastas
INPUT_DIR = "/content/drive/MyDrive/GEE_Export-amazonia_floresta_alagavel_raster_data/tiles"
OUTPUT_DIR = "/content/drive/MyDrive/GEE_Export-amazonia_floresta_alagavel_raster_data"

# Primeiro faça um dry-run para ver o plano
# run(INPUT_DIR, OUTPUT_DIR, dry_run=True)

# Depois execute de verdade
run(INPUT_DIR, OUTPUT_DIR, dry_run=False)

# ⬇️ Nova célula para dividir os mosaicos multi-banda em arquivos por ano

# Define o diretório de entrada para este script (será o OUTPUT_DIR do processo de mosaico)
INPUT_DIR_SPLIT = OUTPUT_DIR # Usamos o OUTPUT_DIR já definido

# Define o diretório de saída para os arquivos de banda única por ano
OUTPUT_DIR_PER_YEAR = os.path.join(OUTPUT_DIR, "per_year")
ensure_dir(OUTPUT_DIR_PER_YEAR)

# Diretório temporário para processamento rápido no Colab
TEMP_SPLIT_DIR = "/content/temp_split_output"
ensure_dir(TEMP_SPLIT_DIR)

def split_multi_band_to_annual(input_multi_band_file, output_per_year_dir, temp_dir):
    print(f"[PROCESSAMENTO] Dividindo {os.path.basename(input_multi_band_file)} em bandas anuais...")
    multi_band_ds = None
    try:
        multi_band_ds = gdal.Open(input_multi_band_file, gdal.GA_ReadOnly)
        if multi_band_ds is None:
            print(f"[ERRO] Não foi possível abrir o arquivo multi-banda para divisão: {input_multi_band_file}")
            return False

        base_name_without_ext = os.path.splitext(os.path.basename(input_multi_band_file))[0]

        for i in range(multi_band_ds.RasterCount):
            band_idx = i + 1
            band_description = multi_band_ds.GetRasterBand(band_idx).GetDescription()
            year = ""
            if band_description and "_" in band_description:
                # Extract year from 'classification_YYYY'
                year = band_description.split('_')[-1]
                if not year.isdigit():
                    year = ""

            # Construct output filename for single band
            single_band_filename = f"{base_name_without_ext}_{year}.tif" if year else f"{base_name_without_ext}_band{band_idx}.tif"
            temp_single_band_path = os.path.join(temp_dir, single_band_filename)
            final_single_band_path = os.path.join(output_per_year_dir, single_band_filename)

            # Check if the single-band file already exists in the per_year folder on Drive
            if os.path.exists(final_single_band_path):
                print(f"  [INFO] Pulando divisão da banda {band_idx} ({final_single_band_path} já existe no Drive).")
                continue

            # Use gdal_translate to extract single band to temp location
            res = subprocess.run([
                "gdal_translate", "-b", str(band_idx),
                "-of", "GTiff",
                "-co", "TILED=YES", "-co", "COMPRESS=LZW", "-co", "PREDICTOR=2",
                "-co", "BIGTIFF=YES", "-co", "SPARSE_OK=TRUE",
                input_multi_band_file, temp_single_band_path
            ], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

            if res.returncode != 0:
                print(f"  [ERRO] gdal_translate falhou ao extrair banda {band_idx}:", res.stderr.strip())
                continue

            # Set band description explicitly for the single band (good practice)
            if band_description and not set_band_descriptions(temp_single_band_path, [band_description]):
                 print(f"  [ALERTA] Falha ao definir descrição de banda para {temp_single_band_path}")

            # Move single band file from temp to final destination on Drive
            try:
                shutil.move(temp_single_band_path, final_single_band_path)
                print(f"  [MOVENDO BANDA ANUAL PARA DRIVE] {final_single_band_path}")
            except Exception as e:
                print(f"  [ERRO] Falha ao mover {temp_single_band_path} para {final_single_band_path}: {e}")
        return True
    except Exception as e:
        print(f"[ERRO] Falha durante a divisão de bandas para {os.path.basename(input_multi_band_file)}: {e}")
        return False
    finally:
        if multi_band_ds:
            multi_band_ds = None # Close dataset

# --- Main execution for splitting ---
print(f"[INICIANDO DIVISÃO] Buscando mosaicos multi-banda em: {INPUT_DIR_SPLIT}")
multi_band_mosaics = list_tifs_recursive(INPUT_DIR_SPLIT) # Re-use list_tifs_recursive for simplicity

if not multi_band_mosaics:
    print("[ALERTA] Nenhum arquivo mosaico multi-banda encontrado para dividir.")
else:
    for mosaic_file in tqdm(multi_band_mosaics, desc="Dividindo mosaicos"):
        if split_multi_band_to_annual(mosaic_file, OUTPUT_DIR_PER_YEAR, TEMP_SPLIT_DIR):
            pass # Success message already printed inside function
        else:
            print(f"[FALHA GERAL] Falha ao processar o mosaico: {mosaic_file}")

print("\n[FINALIZADO DIVISÃO] Arquivos anuais em:", OUTPUT_DIR_PER_YEAR)

# Clean up temporary directory for splitting
if os.path.exists(TEMP_SPLIT_DIR):
    try:
        shutil.rmtree(TEMP_SPLIT_DIR)
        print(f"[LIMPEZA] Diretório temporário de divisão removido: {TEMP_SPLIT_DIR}")
    except Exception as e:
        print(f"[ALERTA] Falha ao remover diretório temporário de divisão {TEMP_SPLIT_DIR}: {e}")

